// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx7wZC1sRpOoMCZIsQuCm5pjxSjLSlVKw',
    appId: '1:904073961868:web:17e24618dbed6f584876a9',
    messagingSenderId: '904073961868',
    projectId: 'chat-with-firebase-46aac',
    authDomain: 'chat-with-firebase-46aac.firebaseapp.com',
    databaseURL: 'https://chat-with-firebase-46aac-default-rtdb.firebaseio.com',
    storageBucket: 'chat-with-firebase-46aac.appspot.com',
    measurementId: 'G-L269Y0LJ82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4ZNCu9soXpGzs97KjeI_-yjM2TVJ9lk',
    appId: '1:904073961868:android:3aa5c70b5585f8154876a9',
    messagingSenderId: '904073961868',
    projectId: 'chat-with-firebase-46aac',
    databaseURL: 'https://chat-with-firebase-46aac-default-rtdb.firebaseio.com',
    storageBucket: 'chat-with-firebase-46aac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0PJLLZZRNG-zkhdutcMGEPHzJ9FM7OOA',
    appId: '1:904073961868:ios:983002d9d37dba9b4876a9',
    messagingSenderId: '904073961868',
    projectId: 'chat-with-firebase-46aac',
    databaseURL: 'https://chat-with-firebase-46aac-default-rtdb.firebaseio.com',
    storageBucket: 'chat-with-firebase-46aac.appspot.com',
    iosClientId:
        '904073961868-d2sntdubgug775maf06avf9so2ahcugp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0PJLLZZRNG-zkhdutcMGEPHzJ9FM7OOA',
    appId: '1:904073961868:ios:8d749dafa79862fd4876a9',
    messagingSenderId: '904073961868',
    projectId: 'chat-with-firebase-46aac',
    databaseURL: 'https://chat-with-firebase-46aac-default-rtdb.firebaseio.com',
    storageBucket: 'chat-with-firebase-46aac.appspot.com',
    iosClientId:
        '904073961868-4tfh2t63p7nmafr50bd55hh11e1atnh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatWithFirebase.RunnerTests',
  );
}
